on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: bradley-mader/bradley-mader.github.io
        ref: main
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: git config --global user.email "mader.bradley@gmail.com"
    - run: git config --global user.name "Bradley Mader"
    - run: git remote set-url origin https://git:${{ secrets.GH_PAGES_SECRET }}@github.com:bradley-mader/bradley-mader.github.io.git
    - run: npm install
    - run: npm run build
    - run: npm run deploy
env:
  GITHUB_TOKEN: ${{ secrets.GH_PAGES_SECRET }}
