on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: bradley-mader/bradley-mader.github.io
        ref: main
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: git config --global user.email "mader.bradley@gmail.com"
    - run: git config --global user.name "bradley-mader"
    - run: npm install
    - run: npm run build
    - run: npm run postbuild
    - uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: out
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
