on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm run install
    - run: npm run build
    - run: npm run deploy
env:
  GITHUB_TOKEN: ${{ github.token }}
