on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "18.4.1"
    - run: npm install
    - run: npm build
    - run: npm deploy
env:
  GITHUB_TOKEN: ${{ github.token }}
